name: once
description: Want to run a piece of code once periodically (Once - Daily - Weekly - Monthly - On new build - On new version - Any period)? We cover your back.
version: 1.6.1
repository: https://github.com/MostafaSolimanMO/once

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_lints: ^3.0.1

topics:
  - utils
  - storage
  - persistence