name: once
description: Want to run a piece of code once periodically (Once - Daily - Weekly - Monthly - On new build - On new version - Any period)? We cover your back.
version: 1.6.3
repository: https://github.com/MostafaSolimanMO/once

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

topics:
  - utils
  - storage
  - persistence