name: once
description: Want to run a piece of code once periodically (Once - Daily - Weekly - Monthly - On new build - On new version - Any period)? We cover your back.
version: 1.7.0
repository: https://github.com/MostafaSolimanMO/once

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5
  package_info_plus: ^8.1.3

dev_dependencies:
  flutter_lints: ^5.0.0

topics:
  - utils
  - storage
  - persistence

platforms:
  android:
  ios: